base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.counter, name='counter'),
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('createpost', views.CreatePost, name='CreatePost'),
    path('post/<int:id>', views.post, name='post'),
    path('home', views.index, name='index'),
    path('update-post/<int:post_id>', views.updatepost, name='update_post'),
    # path('search', views.search_blogs, name='search_blogs'),
    path('delete-post/<int:post_id>/', views.deletepost, name="delete-post"),
    path('share_twitter_post', views.share_twitter_post, name="share_twitter_post"),
    path("tweets/", views.display_shared_tweets, name="tweets"),
    path('like/<int:post_id>', views.like_post, name='like'),
    path('comment/<str:post_id>', views.comment, name='comment'),
    path('languges', views.languges, name='languges'),
    path('blog', views.blog, name='blog'),
    path('updates', views.updates, name='updates'),
    path('userslist', views.userslist, name="users"),
    path('follow/<int:user_id>', views.follow, name="follow")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

#asdfasdf

word_counter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

def follower_choices():
    pass

class Tweet(models.Model):
    title = models.CharField(max_length=200)
    twitter_post_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title



    
    def save(self, *args, **kwargs): # args for posentinal argements kwargs for keyword posentianl argemnets
        super().save(*args, **kwargs)
        for user in self.followers.all():
            user.followings.add(self)
        for user in self.followings.all():
            user.followers.add(self)
        super().save(*args, **kwargs)
        
    
    def __str__(self):
        return self.user.username

class Feature(models.Model):
    name = models.CharField(max_length=123)
    details = models.CharField(max_length=123)

class Post(models.Model):
    likes = models.ManyToManyField(User, blank=True, related_name="post_likes")
    title = models.CharField(max_length=123)
    image = models.ImageField(upload_to='post_image', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class View(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.views)

class Comment(models.Model):
    date = models.DateField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

templates/comment.html
<form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}
    <button>Comment</button>
</form>

templates/createpost.html
{% include 'navbar.html' %}

<form method="POST" enctype="multipart/form-data">
{{form.as_p}}
{% csrf_token %}
<button>Save Post</button>
</form>

templates/delete.html
<Form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{post}}"</p>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm">
</Form>

templates/languges.html
<h1>Coming soon!</h1>

<style>
    h1 {
        color: rgb(0, 0, 0);
        width: auto;

    }
</style>

templates/login.html
<a href="{% url 'index' %}">go back to home</a>
<h1>login below</h1>
<style>
    h6{
        color: red;
    }
</style>{% for message in messages %}
<h6>{{message}}</h6>
{% endfor %}
<form method="POST" action="login">
    {% csrf_token %}
    <p>Username :</p>
    <input type="text" name="username" />
    <p>Password :</p>
    <input type="password" name="password" /><br>
    <input type="submit">
</form>

<h7>dont have an account <a href="{% url 'register' %}">create one</a></h7>

templates/navbar.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>socblog</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body class="p-3 m-0 border-0 bd-example m-0 border-0">

    <!-- Example Code -->
    
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'counter' %}">social blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">socblog</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'counter' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'CreatePost' %}">create post</a>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">register</a>
                </li>
                {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'counter' %}">home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'share_twitter_post' %}">twitter posts</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' user.id %}">profile</a>
              </li>
              {% endif %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'languges' %}" role="button" >
                  language
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>

            </form>
          </div>
        </div>
      </div>
    </nav>
    
    <!-- End Example Code -->
  </body>
</html>

templates/post.html
{% include 'navbar.html' %}
<a href="{% url 'profile' post.author.id %}">@{{post.author}}</a><br>
<a>
    {{post.title}}
</a>
<br>
{% if post.image %}
<img src="{{post.image.url}}" />
{% endif %}
<p>{{post.content}}</p>
<small>{{post.date|timesince}}</small>
<hr>
{% if user.is_authenticated %}
<h6>  {{post.comment_set.count}} comments </h6>
<form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}
    <button>Comment</button>
</form>
{% else %}
<strong>you must create a account if you want to comment</strong>
{% endif %}
{% for comment in post.comment_set.all %}
    <br>
    <a href="{% url 'profile' comment.user.id %}">@{{ comment.user }}</a> <a>{{comment.date|timesince}}</a>
    <p>{{ comment }}</p>
    <hr>
    
{% endfor %}

templates/register.html
<h1>Sign Up Below</h1>
<style>
h6{
    color: red;
}
</style>
{% for message in messages %}
<h6>{{message}}</h6>
{% endfor %}

<form method="POST" action="register">
    {% csrf_token %}
    <p>Username :</p>
    <input type="text" name="username" />
    <p>Email :</p>
    <input type="email" name="email" />
    <p>Password :</p>
    <input type="password" name="password" />
    <p>Repeat Password :</p>
    <input type="password" name="password2" /><br>
    <input type="submit" />
</form>
<li><a class="getstarted scrollto" href="{% url 'login' %}">login or signup</a></li>

templates/search.html
<!-- search.html -->
{% extends 'counter.html' %}

{% block content %}
    <h1>Search Results for "{{ query }}"</h1>
    {% if results %}
        <ul>
            {% for post in results %}
                <li><a href="{% url 'post_detail' post.slug %}">{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Option 1: Include in HTML -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>TodoApp</title>
  </head>
  <body>
    <!-- Header -->
    <header>
      <nav>
        <a href="{% url 'index' %}">TodoApp</a>
        <a href="{% url 'create_todo' %}" id="create-task-btn">
          <span>Create Task</span>
          <i class="bi bi-plus-circle"></i>
        </a>
      </nav>
    </header>

    <section class="main">
      <form action="" method="get">
        <div id="search-todo-container">
          <input
            type="search"
            id="search"
            name="q"
            placeholder="Search todo"
            required
          />
          <i class="bi bi-search"></i>
        </div>
      </form>

      <div class="todo-lists">

        {% for todo in todos %}
        <div class="todo-item">
          <div class="todo-main">
            <h3 class="todo-title">{{ todo }}</h3>
            <p class="todo-task">
              {{ todo.content }}
            </p>
          </div>

templates/share_twitter_post.html
{% include 'navbar.html' %}
<!-- share_twitter_post.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Share Twitter Post</title>
    <!-- Include Twitter widgets.js script -->
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</head>
<body>
    <h1>Share Twitter Post</h1>
    <form method="post">
        {% csrf_token %}
        <p>Enter the Twitter post URL:</p>
        <input type="text" name="twitter_post_url" value="{{ twitter_post_url }}">
        <p>Enter a title for the tweet:</p>
        <input type="text" name="twitter_post_title" value="{{ twitter_post_title }}">
        <input type="submit" value="Share">
    </form>
    {% if twitter_post_url %}
        <div>
            <h2>{{ twitter_post_title }}</h2>
            <blockquote class="twitter-tweet">
                <a href="{{ twitter_post_url }}"></a>
            </blockquote>
        </div>
    {% endif %}
</body>
</html>

templates/updates.html
<div>
<h1>all updates</h1>
<div>
    <h4>update 1:</h4><small>2023/10/28</small>
    <li>added register and login</li>
    <li>added user posting</li>
</div>
<div>
    <h4>update 2:</h4><small>2023/11/20</small>
    <li>added like post</li>
    <li>added views post</li>
    <li>added comment post</li>
    <li>updated design</li>
</div>
<div>
    <h4>update 3:</h4><small>2024/01/12</small>
    <li>added user profile form</li>
    <li>updated navbar</li>
    <li>added search form</li>
</div>
<div>
    <h4>update 4:</h4><small>2024/02/2</small>
    <li>updated user profile</li>
    <li>added bio to profile</li>
</div>
<div>
    <h4>update 5:</h4><small>2024/02/14</small>
    <li>added follow/following form</li>
    <li>added update post</li>
</div>
<div>
    <h4>update 6:</h4><small>2024/02/14</small>
    <li>added delete post</li>
</div>
<h1>incoming updates</h1>
<div>
    <h4>update 7:</h4><small>2024/03/20</small>
    <li>chat rooms</li>
    <li>topics for chat rooms</li>
    <li>the desgin will look better</li>
    <li>post topics</li>
    <li>coming soon languages Arabic, Spanish, Rssain</li>
</div>
<div>
    <h4>update 8:</h4><small>2024/4/1</small>
    <h5>design will look like twitter</h5>
</div>
</div>

templates/userp.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
<!-- Example split danger button -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/users.html
{% for profile in profiles %}
<div>
    <h1>{{profile.user.username}}</h1>
    <a href="{% url 'follow' profile.id %}">follow</a>
</div>
{% endfor %}